### ISSUE TITLE
Citations for dependencies

### ISSUE THREAD

**Issue by JohannesBuchner** [ACCarnall/bagpipes#13]
Dear all,

As you know, developing software is a underappreciated activity in astronomy research. The only reward we can obtain are citations. In the documentation, could you please encourage users to also cite the packages bagpipes is built upon?
Here is an example I have used: https://johannesbuchner.github.io/BXA/#citing-bxa-correctly
pymultinest and multinest seem to be relevant in bagpipes.

Cheers,
            Johannes

**Comment by ACCarnall** [comment]
Hi Johnannes,

If you open up my documentation you will see a similar section that includes a link to your paper already on the front page: https://bagpipes.readthedocs.io

Cheers,
Adam

**Comment by JohannesBuchner** [comment]
Thanks, I see it now!

**Comment by JohannesBuchner** [comment]
(this was triggered by a paper from today praising bagpipes and multinest, lacking a pymultinest citation; I emailed the authors)

**Comment by ACCarnall** [comment]
No problem! By the way, this feels like an opportune moment to remind you of a pull request I submitted to your repository last November. Currently, many bagpipes users have to download pymultinest via my forked repository in order to access unparallelised MultiNest within an MPI environment. It'd be ideal if this functionality could be included in the main branch of the code.

**Comment by JohannesBuchner** [comment]
Unfortunately, this is still happening: https://arxiv.org/pdf/2106.08338.pdf

**Comment by ACCarnall** [comment]
Hi Johannes,

If I remember correctly, last time you requested that I add a link to your paper in my documentation. I pointed out that a link already existed, you said thank you, and no changes were made. So, I don't really understand what you think would be likely to have changed about the situation? 

Whilst I sympathise entirely with your concerns, a.) I had no advance knowledge or sight of the paper you mention, as is often the case for papers using bagpipes; b.) I have no authority to compel bagpipes users to cite your paper, or, for that matter, mine. To the best of my knowledge, nothing about attribution in academic works is included in any of the common open-source software licenses, meaning anyone who chooses to use our code without citing our papers is acting legitimately.

That said, I do also view this as a breach of etiquette, and I'm happy to try to work on any further suggestions you may have for me to reduce the frequency of what I am sure is an entirely innocent mistake. Failing that, I would recommend that you take up these instances directly with the lead authors of the papers concerned, as is apparently already your policy.

Cheers,
Adam

**Comment by JohannesBuchner** [comment]
Yes, sorry, there is nothing more you can do ... I was only lamenting. I really really dislike writing such emails.
All the best and thanks for your work.
