### ISSUE TITLE
Weird Dip before Balmer break for model galaxy

### ISSUE THREAD

**Issue by Ragadeepika-Pucha** [ACCarnall/bagpipes#18]
Hi -

I am trying to create a model galaxy spectrum using Bagpipes, which focuses on the rest-frame UV and optical region. 
I need a model spectrum of a young starburst galaxy. So, I used the following model_components - 

![image](https://user-images.githubusercontent.com/25374269/127546740-ea4e6e94-ccc6-48c5-8c34-43d8b9b84a79.png)

I am using all the filters that are used in the example notebook and created the model galaxy. 
However, it shows a weird dip near the Balmer break region and the expected Balmer break is not clearly visible -

![image](https://user-images.githubusercontent.com/25374269/127546953-513be09b-d4e2-4193-83f3-0c622df861cd.png)

However, if I include `t_bc` in the model parameters - it does not change much until t_bc = 0.001. For this value, the spectrum changes - 

![image](https://user-images.githubusercontent.com/25374269/127547378-7fb180ef-596b-4ccb-b667-e1edcafe89c2.png)

Can you please help me with why I am getting such results and how to fix it?

Thanks,
Raga

**Comment by ACCarnall** [comment]
Hi Raga,

I'm sorry I don't know how I missed this when you first posted it.

I suspect what you're seeing in the first case is a large component from nebular continuum emission, which looks quite different from the stellar continuum people are most used to looking at. This can dominate for particularly highly star-forming galaxy models.

If you don't include t_bc in your model_components, it gets set to 0.01 by default, so by setting it to 0.001 you're reducing the nebular contribution to the spectrum by saying only the spectra of stars below 0.001 Gyr in age get passed through the nebular emission model.

Larger Balmer/4000A breaks are associated with older stellar populations - 0.1 Gyr is still very young, so you wouldn't expect to see a lot of Balmer break even without the nebular continuum. If you increase the age of the oldest stars to something more like 1 Gyr you'll start to see a much more obvious Balmer break in the predicted spectrum.

Hope this helps, and sorry for the delay in getting back to you.

Cheers,
Adam
