### ISSUE TITLE
issue with adding a JWST/MIRI photometric band when generating a model galaxy spectrum?

### ISSUE THREAD

**Issue by Vladan1986** [ACCarnall/bagpipes#26]
Hello,

I have an issue when I want to generate a model galaxy spectrum with predictions for photometric fluxes for an example galaxy with HST and JWST filters.

When I add all the available filters for this galaxy, including the MIRI F770W filter (in the attachment) I obtain 1 data point that seems to be <1 in the x axis log space, so lambda seems to be negative (Fig. 2). If I remove the F770W filter, I obtain Fig. 1.

I tried removing the 0 and < 10^{-11} flux values from the F770W throughput values, but that didn't solve the issue.
Any suggestion or help is welcome.

Cheers,
[F770W.csv](https://github.com/ACCarnall/bagpipes/files/9627532/F770W.csv)
![fig-1](https://user-images.githubusercontent.com/35525863/191796484-e22c8a6d-2450-4d48-9052-f8920a1161b6.png)
![fig-2](https://user-images.githubusercontent.com/35525863/191796491-b69aa90e-4909-452c-b7e4-a96d4d88cfe7.png)

**Comment by ACCarnall** [comment]
Hi Vladan, 

The wavelengths in that file seem to be in microns, you'll need to convert them to angstroms. Also, I don't know if the code will cope with a csv file, probably safest to replace the commas with spaces.

Cheers,
Adam

**Comment by Vladan1986** [comment]
Hi Adam, 

Thank you very much for your help!

Cheers,
Vladan
