### ISSUE TITLE
Fitting short wavelength ranges

### ISSUE THREAD

**Issue by PatrickOgle** [ACCarnall/bagpipes#28]
I am having trouble fitting a high SNR, medium spectral resolution spectrum of a relatively narrow wavelength range
of a galaxy bulge, with no photometry included. The fit runs forever (tried overnight) without yielding a result.
Is bagpipes capable of fitting such data, or is it lost in parameter space since the model is relatively insensitive to 
parameter variations in this wavelength range?  Any suggestions on how to coax bagpipes to converge on a solution
in this case? Thanks!

![bulge_spec](https://user-images.githubusercontent.com/44263689/193053755-de183cc4-3764-4a67-ad96-d4d57986868a.png)

**Comment by ACCarnall** [comment]
Hi Patrick,

Hard to know without more detail about exactly what you're doing whether I'd have expected the fit to converge in that time (how many CPUs, how many wavelength points, what kind of model). I wouldn't expect any specific problem fitting this sort of data however. I'd suggest as a first check trying to simplify down the model you're fitting to as few parameters as possible (maybe also binning your spectrum as coarsely as possible) and seeing if you can get a fit to converge. This should hopefully help you understand whether everything is working properly before adding back in complexity.

Cheers,
Adam
