### ISSUE TITLE
Is logU parameter fixed or it can be fitted in a given range?  

### ISSUE THREAD

**Issue by Vladan1986** [ACCarnall/bagpipes#30]
Hi, 

Sorry, this could be a naive question, I am new with Bagpipes. I have a question regarding the nebular parameter logU. I have seen in some of the examples here that is always used as a fixed parameter both with generating a model and when fitting (e.g. `nebular["logU"] = -3`.)

I tried to use it also as a parameter that should be fitted, by giving a certain range of values (e.g. nebular["logU"] = (-3., -0.5). But the MCMC doesn't seem to fit this parameter, it is not in the corner plot or in the fit.posterior.samples object.

Is it possible to fit this parameter ? Thank you.

Cheers,
Vladan

**Comment by ACCarnall** [comment]
Hi Vladan,

The parameter can certainly be fitted, though by default the allowed range is only from -4 to -2. I would expect the code to crash if you set one of your parameter limits outside this range. Can you check you added the nebular dictionary to the fit_instructions dictionary? If so, can you please send me across your fit_instructions dictionary and I'll investigate.

Cheers,
Adam

**Comment by Vladan1986** [comment]
Hi Adam, 

Thank you for the quick reply. Yes, it seems that was my problem, I was not using the allowed range of values. 
Now I am able to fit the logU parameter and it appears in the corner plots and in the fit.posterior.samples.

Thanks for the help!

Cheers,
Vladan
