### ISSUE TITLE
Possible updates on the nebular emission model with a wider range on logU parameter

### ISSUE THREAD

**Issue by Vladan1986** [ACCarnall/bagpipes#36]
Hello, 

I was wondering if there are any possible plans on updating the nebular component of the SED model, particularly on the allowed prior limits on the logU parameter (considering there are some recent works showing  logU ~ [-1.5, -2.5] for high-redshift galaxies)?

Thank you in advance.
Cheers,
Vladan

**Comment by ACCarnall** [comment]
Hi Vladan,

Please take a look at #31  which should have the instructions you need.

Cheers,
Adam

**Comment by ACCarnall** [comment]
The standard version of the code now comes with nebular models from logU = -4 to 0.
