### ISSUE TITLE
Issue with galaxy.plot()

### ISSUE THREAD

**Issue by kmlgould** [ACCarnall/bagpipes#38]
hi Adam,

I found a possible bug in the galaxy.plot() function, originating from plot_spectrum.py. In line 53, `ax.fill_between(spectrum[:, 0], lower, upper, color=color,  zorder=zorder-1, alpha=0.75, linewidth=0)`, lower and upper are passed as generators, but according to the [documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.fill_between.html) they should be passed as arrays (or lists). 

For me, this showed up as an error which said `"TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`, which I found can be fixed by passing upper and lower as lists instead.

**Comment by ACCarnall** [comment]
Hi Kate,

A few people have been having these sorts of problems recently, e.g., see #34 - this might be the solution? Also I think sometimes this issue arises when the photometry and spectroscopy you're feeding it have very different normalisations, might be worth checking this too.

Cheers,
Adam

**Comment by ACCarnall** [comment]
I believe this should now be fixed in v1.0.2.
