### ISSUE TITLE
kernel dies during SED fit

### ISSUE THREAD

**Issue by jjangdol0011** [ACCarnall/bagpipes#46]
Hi,

Thank you for creating a public code first! I am having an error downloading MultiNest to use bagpipes.

Even after setting the LD_LIBRARY_PATH, the following error occurred when trying to import bagpipes in jupyter notebook:

import bagpipes
->
ERROR: Could not load MultiNest library: libmkl_gf_lp64.so.2
ERROR: You have to build MultiNest,
ERROR: and point the LD_LIBRARY_PATH environment variable to it!
ERROR: manual: https://johannesbuchner.github.io/PyMultiNest/install.html

problem: libmkl_gf_lp64.so.2: cannot open shared object file: No such file or directory
Bagpipes: PyMultiNest import failed, fitting will be unavailable.

"libmkl_gf_lp64.so.2" was not found in my MultiNest/lib directory even after I build MultiNest.

After searching for the file within my team server, I found the file above and added the path to LD_LIBRARY_PATH as well:
export LD_LIBRARY_PATH=/opt/intel/oneapi/mkl/2022.1.0/lib/intel64/:$LD_LIBRARY_PATH

Since running this code, I am able to import bagpipes, but as soon as I try to run the "fit.fit" in Example 3 - Fitting photometric data from https://github.com/ACCarnall/bagpipes/blob/master/examples/Example%203%20-%20Fitting%20photometric%20data%20with%20a%20simple%20model.ipynb,
 the kernel dies.

Do you have any idea what the problem might be and if there is a possible solution?

Thanks in advance
Minseong.

**Comment by ACCarnall** [comment]
I'm afraid this is a multinest installation issue rather than anything to do with Bagpipes. Please take a look at my answer to #45 which might be helpful.
