### ISSUE TITLE
Line fluxes in fit

### ISSUE THREAD

**Issue by mariabile** [ACCarnall/bagpipes#47]
Hello, 
is it possible to fix some line fluxes in the fitting? I have a galaxy with several photometric points and a  couple of line fluxes that I want to include. Is that possible=

**Comment by ACCarnall** [comment]
Hi there, fitting line fluxes isn't currently something the code supports, but you can fit line equivalent widths. I've attached some example code on how to do this.

[indices_example.txt](https://github.com/ACCarnall/bagpipes/files/11816896/indices_example.txt)

**Comment by mariabile** [comment]
Thanks so much.
What units the index needs to be?

**Comment by mariabile** [comment]
Hello,
thank you so much! in the example what kind of units are used?
