### ISSUE TITLE
Using BPASS stellar and nebular grids  instead of BC03?

### ISSUE THREAD

**Issue by Vladan1986** [ACCarnall/bagpipes#49]
Hello, 

I wanted to ask the usage of the BPASS stellar and nebullar grids with BAGPIPES. 

So, I wanted to use the BPASS stellar and nebular grids instead of BC03, but I wasn't able to find the .fits files (e.g., "bpass_2.3_bin-imf135_300_a+06_stellar_grids.fits")  in the  /bagpipes/models/grids/ folder or any other folder in the last few versions of Bagpipes. So far, I have also been unsuccessful in finding them online. 

Can you direct me to where I can find these files? Any help is more than welcome. Thanks in advance!

Cheers,
Vladan

**Comment by ACCarnall** [comment]
Hi Vladan,

Sorry, where are you seeing that file name? That file is a grid I made of the most alpha enhanced models in the bpass v2.3 release. There shouldn't be any references to it in the code, unless I forgot to remove a comment somewhere?

The working version of bagpipes+bpass uses the bpass v2.2 models, with grids and an edited config.py file available from: https://drive.google.com/drive/folders/1R8SyXfqyHh4691WwAe_TF2FvYntI1PvN?usp=sharing

Cheers,
Adam

**Comment by Vladan1986** [comment]
Hi Adam, 

It is a line in the config_bpass.py file of the BAGPIPES versions 1.0.2. 

Thanks for the link and a quick reply.

Cheers,
Vladan

**Comment by ACCarnall** [comment]
Ah ok thanks, I should probably clean that up.
