### ISSUE TITLE
`mpi_off` unexpected keyword

### ISSUE THREAD

**Issue by omrygin** [ACCarnall/bagpipes#5]
Hello,
When running with `mpirun`, with `mpi_serial=True`, I receive an error `TypeError: run() got an unexpected keyword argument 'mpi_off'` in fitting/fit.py. This is an error when calling run() of PyMultiNest. I went to the PyMultiNest repository and downloaded the latest version, and the issue remained. When I turn mpi_serial=False, the issue is lifted.

**Comment by ACCarnall** [comment]
Hi there,

Please refer to this page in the documentation (bottom paragraph): https://bagpipes.readthedocs.io/en/latest/fitting_catalogues.html

I've had to make some modifications to the pymultinest repository for this specific feature, which unfortunately the owner doesn't seem to want to accept as a pull request. This means I've had to set up my own version of the pymultinest repository to get this feature working, you can download it from here: https://github.com/ACCarnall/pymultinest

Cheers,
Adam

**Comment by omrygin** [comment]
Solved the issue
