### ISSUE TITLE
MIssing condition in model wavelength setup

### ISSUE THREAD

**Issue by rmendsley** [ACCarnall/bagpipes#51]
Hi Adam,

I was trying to run a test photometry+spectrum fit that happened to be a case where the minimum and maximum wavelength bounds for the photometric bands fell entirely within the input spectrum wavelength regime. That condition isn't dealt with in the `_get_wavelength_sampling` function of the `models/model_galaxy.py` script. That is, you're missing a condition where:
`self.spec_wavs[0] < self.filter_set.min_phot_wav and self.spec_wavs[-1] > self.filter_set.max_phot_wav`. The resulting error was something like 'model_galaxy does not have attribute self.R' during the fit step.

I was able to resolve this and get the fit running by just throwing in a fake, very high noise photometric data point in a very blue band, but thought you might want to edit the code to include this case.

Cheers,
Ryan

**Comment by ACCarnall** [comment]
This has now been fixed in the code.
