### ISSUE TITLE
Flux Upper Limits

### ISSUE THREAD

**Issue by jsulli27** [ACCarnall/bagpipes#57]
Hello,

Is Bagpipes able to handle an upper limit on the flux in a filter? If so, how should I load in the photometry for Bagpipes so the code knows to treat a flux value as an upper limit?

Best,
Jessica Sullivan

**Comment by ACCarnall** [comment]
Hi Jessica,

Upper limits are just normal data for which you don't have sufficient SNR to confidently detect the object. So you might have a flux of -0.1+/- 0.5 microJanskys, which you'd call a 3 sigma upper limit at 1.4 or 1.5 microJanskys. The statistically rigorous way to include these datapoints in fitting is to treat them just like any other, by feeding bagpipes the measured flux and 1 sigma uncertainty.

The only time this is likely to cause a problem is when you don't have a good handle on your errors, so for example if you have a flux of -5+/- 0.5 microJanskys it's unlikely this is the real flux/error, and that you instead have some sort of problem with your data reduction. In this case you probably need to go back and fix this before trying to include the data in your fit.

Cheers,
Adam

**Comment by Gamiro00** [comment]
Hi, I am also having the same issue, so my question is if we should feed bagpipes with the "-0.1+/- 0.5 microJanskys" flux or the "1.4+/-0.5"  as the measured flux.
