### ISSUE TITLE
bagpipes kills my ipynb kernel

### ISSUE THREAD

**Issue by HeloiseS** [ACCarnall/bagpipes#6]
Bagpipes repeatedly killed my kernel. I tracked it down to this error being returned from MultiNest:

```
Bagpipes: fitting object 118

 *****************************************************
 MultiNest v3.10
 Copyright Farhan Feroz & Mike Hobson
 Release Jul 2015

 no. of live points =  400
 dimensionality =    3
 resuming from previous job
 *****************************************************
 ERROR: live points file has less than          400  points.
 Aborting
```

I got around the error above by changing the name of the run. No idea why it occured or how that fixed it.

**Comment by ACCarnall** [comment]
Hey Heloise,

Were you previously running with <400 live points? If so you need to delete the MultiNest output files and start the run again. You can tell it's trying to load existing output files by the "resuming from previous job" line, if something's going wrong and you see this line it's a fair bet you need to delete the output files!

Cheers,
Adam

**Comment by HeloiseS** [comment]
Hey Adam!

I never changed the number of points, and yes after your advice form last week I've realised that either deleting the output files or starting a fresh run is a good idea. I guess my question was more ipynb related and whether there are things I should avoid in jupyter that might kill my notebook or cause extra bugs (for context, I've had issues in jupyter with bagpipes before: the first time I tried to run an example it ran for 2.5 hrs in jupyter and never finished but took only 3 min when run from a script - biggest mystery so far but fortunately it's not happened since). 

Thanks for your help :D

**Comment by ACCarnall** [comment]
Hmm, that's strange, I've never had issues, although I don't use Jupyter very much. Typically I run bagpipes from the terminal with MPI in order to speed things up, and only ever load and post-process the results in Jupyter.

If you hadn't change the number of live points my guess would be that the previous run was terminated whilst it was in the process of writing the current live points to file, meaning there weren't enough of them when it went back to look. I've found it's fairly easy for the MultiNest outputs to get corrupted in various ways when stopping and starting in the middle of a run.

**Comment by HeloiseS** [comment]
Hmmm yeah i may have interupted the kernel (cant remember but it sounds like something i would do hahaha).

I'll keep in mind that MultiNest is a little touchy. Cheers :)

**Comment by HinLeung622** [comment]
I seem to be getting a similar issue, but only when using the GP capabilities to fit spectroscopic data.
When running the pipes.fit() command, bagpipes will throw a continuous recurring stream of the same error:
```
NameError                                 Traceback (most recent call last)
_ctypes/callbacks.c in 'calling callback function'()

~/anaconda3/lib/python3.8/site-packages/pymultinest/run.py in loglike(cube, ndim, nparams, lnew, nullcontext)
    214                         if Prior:
    215                                 Prior(cube, ndim, nparams)
--> 216                         return LogLikelihood(cube, ndim, nparams)
    217 
    218 	def dumper(nSamples,nlive,nPar,

~/anaconda3/lib/python3.8/site-packages/bagpipes/fitting/fitted_model.py in lnlike(self, x, ndim, nparam)
    148 
    149         if self.galaxy.spectrum_exists and self.galaxy.index_list is None:
--> 150             lnlike += self._lnlike_spec()
    151 
    152         if self.galaxy.photometry_exists:

~/anaconda3/lib/python3.8/site-packages/bagpipes/fitting/fitted_model.py in _lnlike_spec(self)
    204                                  "with manually specified covariance matrix.")
    205 
--> 206             self.noise = noise_model(self.model_components["noise"],
    207                                      self.galaxy, model)
    208         else:

~/anaconda3/lib/python3.8/site-packages/bagpipes/fitting/noise.py in __init__(self, noise_dict, galaxy, spectral_model)
     44 
     45         if "type" in list(self.param):
---> 46             getattr(self, self.param["type"])()
     47 
     48         else:

~/anaconda3/lib/python3.8/site-packages/bagpipes/fitting/noise.py in GP_exp_squared(self)
     66         length = self.param["length"]
     67 
---> 68         kernel = norm**2*kernels.ExpSquaredKernel(length**2)
     69         self.gp = george.GP(kernel)
     70         self.gp.compute(self.x, self.y_err*scaling)

NameError: name 'kernels' is not defined
```
This error appears over and over again, until bagpipes print the completing message:
Completed in 54.3 seconds.

Followed by another error message:
```
ValueError                                Traceback (most recent call last)
<ipython-input-8-00a29eba1078> in <module>
      1 fit = pipes.fit(galaxy, fit_instructions, run="test_GP2")
      2 
----> 3 fit.fit(verbose=False)

~/anaconda3/lib/python3.8/site-packages/bagpipes/fitting/fit.py in fit(self, verbose, n_live, mpi_off)
    141 
    142             # Load MultiNest outputs and save basic quantities to file.
--> 143             samples2d = np.loadtxt(self.fname + "post_equal_weights.dat")
    144             lnz_line = open(self.fname + "stats.dat").readline().split()
    145 

~/anaconda3/lib/python3.8/site-packages/numpy/lib/npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows)
   1157         # converting the data
   1158         X = None
-> 1159         for x in read_data(_loadtxt_chunksize):
   1160             if X is None:
   1161                 X = np.array(x, dtype)

~/anaconda3/lib/python3.8/site-packages/numpy/lib/npyio.py in read_data(chunk_size)
   1085 
   1086             # Convert each value according to its column and store
-> 1087             items = [conv(val) for (conv, val) in zip(converters, vals)]
   1088 
   1089             # Then pack it according to the dtype's nesting

~/anaconda3/lib/python3.8/site-packages/numpy/lib/npyio.py in <listcomp>(.0)
   1085 
   1086             # Convert each value according to its column and store
-> 1087             items = [conv(val) for (conv, val) in zip(converters, vals)]
   1088 
   1089             # Then pack it according to the dtype's nesting

~/anaconda3/lib/python3.8/site-packages/numpy/lib/npyio.py in floatconv(x)
    792         if '0x' in x:
    793             return float.fromhex(x)
--> 794         return float(x)
    795 
    796     typ = dtype.type

ValueError: could not convert string to float: '0.695326704962314428-309'
```
But the galaxy was not actually fitted.

If I were to kill the process when it is looping through the 'kernels' is not defined error, the jupyter notebook kernel will die shortly after.

I tried the same code in script form ran in terminal, and the same thing happens.

Any thoughts?

OS = Ubuntu Linux
python = 3.8
bagpipes = installed 1 month ago

**Comment by ACCarnall** [comment]
Hi Hin,

This is most likely happening because you don't have the george python module installed. The code currently tries to import george.kernels, but doesn't do anything if it's not available, as the vast majority of the time it's not needed. Try pip installing the george module (may need some non-python dependencies) and run the code again.

Cheers,
Adam

**Comment by HinLeung622** [comment]
Thank you very much! That seems to have solved the problem!

Hin
