### ISSUE TITLE
Numpy 1.25 support - deprecation error with 'R_curve'

### ISSUE THREAD

**Issue by pietro31700** [ACCarnall/bagpipes#60]
Hello,

Since Numpy 1.25.0 a previous warned behavior has become deprecated.
In particular in fitting/fitted_model.py the lines:

`if all_vals[i] in all_keys:`

and

`if all_vals[i] == "dirichlet":`

raise an exception if a custom _R_curve_ is specified, because of the 2D array nature of the _R_curve_ value.

I can suggest to put a `if not all_keys[i] == 'R_curve'` containing this two previous `if`. There shouldn't be any loss of generality because of the unique meaning of the _R_curve_ key

For further information:
[https://numpy.org/doc/stable/release/1.25.0-notes.html](url)

**Comment by ACCarnall** [comment]
Thanks for this, would you like to submit a pull request with the changes or should I go ahead and make them?

**Comment by pietro31700** [comment]
Ok, I'll submit the pull request

**Comment by ACCarnall** [comment]
Fixed by #61 , I will release a new version of the code including this soon.

**Comment by ACCarnall** [comment]
Just to say that's v1.0.4 with this update included available via pypi now, thanks for the help!
