### ISSUE TITLE
AGN component

### ISSUE THREAD

**Issue by mariabile** [ACCarnall/bagpipes#62]
Hi Adam,
I was wondering how is it possible to include an AGN component into the fitting as in your nature paper? Is that included somewhere in BAGPIPES?
Thanks so much!

**Comment by ACCarnall** [comment]
Yes this is possible, here are the instructions for the AGN component as included in the paper. Note that this just includes a broken power law and broad Ha and Hb components, it's not a full AGN model.

    agn_comp = {}
    agn_comp["hanorm"] = (0., 25.*10**-18)
    agn_comp["f5100A"] = (0., 10**-19)
    agn_comp["sigma"] = (1000., 5000.)
    agn_comp["sigma_prior"] = "log_10"

    agn_comp["alphalam"] = (-2., 2.)
    agn_comp["alphalam_prior"] = "Gaussian"
    agn_comp["alphalam_prior_mu"] = -1.5
    agn_comp["alphalam_prior_sigma"] = 0.5

    agn_comp["betalam"] = (-2, 2.)
    agn_comp["betalam_prior"] = "Gaussian"
    agn_comp["betalam_prior_mu"] = 0.5
    agn_comp["betalam_prior_sigma"] = 0.5
    
    fit_instructions["agn"] = agn_comp
