### ISSUE TITLE
L_IR

### ISSUE THREAD

**Issue by mariabile** [ACCarnall/bagpipes#65]
Hello,  Is the integrate infrared luminosity a direct output from BAGPIPES?

**Comment by ACCarnall** [comment]
No sorry it doesn't do this by default. If you want to calculate it, the spectrum_full array in fit.posterior.samples should let you do this. The corresponding rest-frame wavelengths are stored in fit.posterior.model_galaxy.wavelengths. If these things don't exist you'll need to run fit.posterior.get_advanced_quantities() first to populate those arrays. If you're running a bunch of objects through the fit_catalogue interface you can use the analysis_function keyword argument to automate the process (see https://bagpipes.readthedocs.io/en/latest/fitting_catalogues.html).
