### ISSUE TITLE
Issues with MPI fork() when trying to modify fit_object in fit_catalogue.py

### ISSUE THREAD

**Issue by omrygin** [ACCarnall/bagpipes#7]
Hi,
I tried to modify fit_catalogue.py to allow plotting individual IDs from the catalog (and not necessarily either all or nothing). These are very small changes, please see the comparison with my branch: https://github.com/ACCarnall/bagpipes/compare/master...omrygin:master

When I run tests (**without mpirun**), the run crashes and I get:
`A process has executed an operation involving a call to the "fork()" system call to create a child process...`

**Comment by ACCarnall** [comment]
Hi there,

I'm afraid I don't know what's causing that. I'd recommend just re-ordering your IDs so that the ones you want to plot are at the start, then killing the process and switching make_plots to False for the rest.

Cheers,
Adam

**Comment by omrygin** [comment]
This is not a solution to the issue, just a different approach to the end-goal. 
I can basically use the example in notebook 3 to reload the fitted object and plot the desired figures.
