### ISSUE TITLE
SEDs of different components

### ISSUE THREAD

**Issue by mariabile** [ACCarnall/bagpipes#70]
Hello,
I was wondering if it is possible in BAGPIPES, in case of multiple components for the SFHs or in case of the addiction of the AGN, if it is possible to get the SEDs of the different components?

**Comment by arielwrl** [comment]
I don't know if there is a built-in way of doing that. The way I have been doing this is by creating a new model using the parameters that were derived for one of your components, and then you can get the SED (as well as other information) from this new model.

**Comment by arielwrl** [comment]
Also here's a sample code that does just that to get the stellar mass of a single component: https://github.com/arielwrl/HST_blobs/blob/main/BAGPIPES/get_young_masses.py
