### ISSUE TITLE
Iyer SFH Modeling

### ISSUE THREAD

**Issue by MohammadRih** [ACCarnall/bagpipes#73]
Hi,

I'm trying to use iyer sfh for my project but I have issues to do this. After 5 seconds, the fitting process is completed, but it does not provide us with any useful output. Even no error is given except a series of warnings. I will be very happy if you have any solution.
some line of warnings are provided at bellow.

{RuntimeWarning: divide by zero encountered in log10
  self.stellar_mass = np.log10(np.sum(self.live_frac_grid*self.ceh.grid))
RuntimeWarning: divide by zero encountered in log10
  self.formed_mass = np.log10(np.sum(self.ceh.grid))}

Thanks

**Comment by jacqdanso** [comment]
Hi! I encountered a similar issue with the Iyer SFH. It turns out it needs to be passed as fit_instructions["iyer2019"] = iyer and not fit_instructions["iyer"] = iyer, as it's been hardcoded as the former in the source code. This worked for me, so hopefully it helps!

**Comment by ACCarnall** [comment]
Please could you let me know which version of bagpipes and which version of dense basis you're using? The fit_instructions dictionary you're trying to use would also be very helpful.

**Comment by ACCarnall** [comment]
Ah ok brilliant, glad you managed to get it working. For further info of this kind I would recommend having a look at Kartheik Iyer's 2019 (and later) papers, he's really better qualified to explain this stuff than I am, I just implemented his work into the code.

**Comment by MohammadRih** [comment]
Thanks
Ok, I'll look at these ref and try to understand it.
