### ISSUE TITLE
Fitting individual object vs fit catalogue producing two different results

### ISSUE THREAD

**Issue by shruti-ramaiya** [ACCarnall/bagpipes#76]
Hi,

I'm currently looking at fitting an object and have played around with changing priors and model components to fit an SED model to photometric data points. I've noticed some odd behaviour however when fitting the same object using two different methods. When I fit my object individually, using the bagpipes.fit() method, it gives a fit as such,

<img width="989" alt="Screenshot 2024-05-29 at 16 22 56" src="https://github.com/ACCarnall/bagpipes/assets/95286997/ec5c8a48-ef91-4827-b22c-2b7582cac401">

When I run this code on a sample of galaxies, the fit looks like this,

<img width="1280" alt="Screenshot 2024-05-29 at 16 24 46" src="https://github.com/ACCarnall/bagpipes/assets/95286997/7e1b0a74-646f-4289-9c05-1a5a0abce06b">

I dont know what the reason for this is. I have checked many times that the priors are the exact same - all I've done is made a copy of my original notebook and changed the bagpipes.fit() to bagpipes.fit_catalogue(). Nothing else is different and ive made sure of this by recreating the notebook multiple times but still this persists. I even tried just using the fit_catalogue method to just fit the same object individually (incase a previous other galaxy fit messed up and it affected a subsequent one somehow) but results still differ. I also make sure to delete the pipes folder before I run my code. What ive also  noticed is that even running the same notebook multiple times will sometimes give different results, even if the pipes folder is deleted and all I do is restart and run Jupyter.

I would be grateful if anyone had any insights into why this is happening

Thanks

**Comment by ACCarnall** [comment]
As with many algorithms for sampling from posterior distributions, nested sampling includes random elements, which mean that the answers for two identical runs will never be exactly the same. This is nothing to do with using fit vs fit_catalogue. This is particularly likely to result in big differences for difficult (i.e. high dimensional or highly degenerate) parameter spaces. The best way to obtain consistent results is to increase the number of live points (n_live parameter), which determines how carefully the algorithm explores parameter space. Typically I would expect a value from around 1000-2000 to return consistent results in most cases. Whilst keeping the redshift of a galaxy fixed it's normally possible to get away with fewer, say 500 or so.

**Comment by shruti-ramaiya** [comment]
Hi Adam,

Thanks for getting back to me and for letting me know why this can happen - that's helpful to know, I'd fixed the redshift for this but and I'll go ahead and change n_live and see if that helps consistency,

Cheers,
Shruti
