### ISSUE TITLE
problem with the Example 3 notebook 

### ISSUE THREAD

**Issue by wzf0312** [ACCarnall/bagpipes#78]
Hi,
I am new to bagpipes and I get stuck in the Example 3 notebook. I run each cell step by step but this **fit.fit(verbose=False)** line kept failing. Here lays the error log. 
{
	"name": "AttributeError",
	"message": "dlsym(RTLD_DEFAULT, run): symbol not found",
	"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[13], line 3
      1 fit = pipes.fit(galaxy, fit_instructions)
----> 3 fit.fit(verbose=False)

File ~/anaconda3/envs/stenv/lib/python3.11/site-packages/bagpipes/fitting/fit.py:190, in fit.fit(self, verbose, n_live, use_MPI, sampler, n_eff, discard_exploration, n_networks, pool)
    187 os.environ[\"PYTHONWARNINGS\"] = \"ignore\"
    189 if sampler == \"multinest\":
--> 190     pmn.run(self.fitted_model.lnlike,
    191             self.fitted_model.prior.transform,
    192             self.fitted_model.ndim, n_live_points=n_live,
    193             importance_nested_sampling=False, verbose=verbose,
    194             sampling_efficiency=\"model\",
    195             outputfiles_basename=self.fname, use_MPI=use_MPI)
    197 elif sampler == \"nautilus\":
    198     n_sampler = Sampler(self.fitted_model.prior.transform,
    199                         self.fitted_model.lnlike, n_live=n_live,
    200                         n_networks=n_networks, pool=pool,
    201                         n_dim=self.fitted_model.ndim,
    202                         filepath=self.fname + \".h5\")

File ~/anaconda3/envs/stenv/lib/python3.11/site-packages/pymultinest/run.py:285, in run(LogLikelihood, Prior, n_dims, n_params, n_clustering_params, wrapped_params, importance_nested_sampling, multimodal, const_efficiency_mode, n_live_points, evidence_tolerance, sampling_efficiency, n_iter_before_update, null_log_evidence, max_modes, mode_tolerance, outputfiles_basename, seed, verbose, resume, context, write_output, log_zero, max_iter, init_MPI, dump_callback, use_MPI)
    283 \tMPI.COMM_WORLD.Barrier()
    284 else:
--> 285 \tlib.run(*args_converted)
    286 if not is_thread:
    287 \tsignal.signal(signal.SIGINT, prev_handler)

File ~/anaconda3/envs/stenv/lib/python3.11/ctypes/__init__.py:389, in CDLL.__getattr__(self, name)
    387 if name.startswith('__') and name.endswith('__'):
    388     raise AttributeError(name)
--> 389 func = self.__getitem__(name)
    390 setattr(self, name, func)
    391 return func

File ~/anaconda3/envs/stenv/lib/python3.11/ctypes/__init__.py:394, in CDLL.__getitem__(self, name_or_ordinal)
    393 def __getitem__(self, name_or_ordinal):
--> 394     func = self._FuncPtr((name_or_ordinal, self))
    395     if not isinstance(name_or_ordinal, int):
    396         func.__name__ = name_or_ordinal

AttributeError: dlsym(RTLD_DEFAULT, run): symbol not found"
}

I would appreciate it if anyone could help me with this issue. 

Sincerely, 
wzf0312

**Comment by ACCarnall** [comment]
Hi there,

I've just checked and I was able to run Example 3 against the most recent version of bagpipes (v1.1.2). I did some googling of your error message and this looks to me like an issue with your multinest installation, e.g., [see this stackoverflow thread](https://stackoverflow.com/questions/61939257/attributeerror-dlsymrtld-default-run-symbol-not-found-meaning).

If you can't get multinest to install properly you can always just uninstall pymultinest and bagpipes should default to using the Nautilus sampler instead, which is pure python so ought to be less susceptible to installation issues.

Cheers,
Adam

**Comment by wzf0312** [comment]
Thank you so much! I will turn to using Nautilus instead.
