### ISSUE TITLE
Ionisation potentials and line fluxes in BAGPIPES

### ISSUE THREAD

**Issue by jamesesdaile** [ACCarnall/bagpipes#8]
Hi Adam,

Was playing around with BAGPIPES model galaxies with different ionisation potentials and after plotting the line fluxes versus ionisation potential it looks like there's some strange behaviour.

![ionisation_potential_linefluxes](https://user-images.githubusercontent.com/17152082/82288277-7a802380-99e5-11ea-8ea5-62d02fd5f4d0.png)

The points are the line fluxes for different species. The blue line I've drawn by hand to show what I expected to see. From your code it looks like you are interpolating from discrete ionisation potentials [-4, -3.5, -3, -2.5, -2]. Could this be a bug related to interpolation?

Cheers,
James

**Comment by ACCarnall** [comment]
Hi James,

Hmm, that's a bit concerning, thanks for pointing it out! To be honest I'm not aware of anyone having used this feature yet, people typically fix logU to one of the grid point values. 

I'll look into this asap, in the mean time could you possibly send me the script that makes this plot? My email address is adamc@roe.ac.uk.

Cheers,
Adam

**Comment by ACCarnall** [comment]
Hey James,

Thanks again for bringing this to my attention, and sorry for the delay in fixing it. I've found the bug which was, as you suggested, in the interpolation routine within the nebular model class. 

The interpolation is still fairly sparse, and linear between the grid points, so the curves don't look quite as smooth as one might hope, however the size of the model grid and number of parameters being interpolated mean these choices are, in my opinion, still right for keeping the general purpose version of the code running as quickly as possible. 

That said, if this isn't good enough for what you want to do I'd be happy to work with you on some local changes to your version that might improve things.

Cheers,
Adam
