### ISSUE TITLE
Line width of fitted lines

### ISSUE THREAD

**Issue by mromano93** [ACCarnall/bagpipes#80]
Hello,

Is there any possibility to retrieve the width of the lines (apart from their integrated fluxes) from the best fit of a spectrum?

Best,
Michael Romano

**Comment by mromano93** [comment]
Hi, sorry for not specifying, I was indeed referring to FWHM of the lines. I was wondering if the code is providing such an information.

Best,
Michael

**Comment by ACCarnall** [comment]
Velocity width is only fitted if you include the "veldisp" keyword in your fit instructions. This is the line sigma width, so you'll need to multiply by 2.35 to get the FWHM.
