### ISSUE TITLE
RuntimeError: Failed to process string with tex because dvipng could not be found

### ISSUE THREAD

**Issue by dongj17** [ACCarnall/bagpipes#87]
Hi! I'm new to Bagpipes. When I run Example 1 and use `fig=model.plot(), fig=model.sfh.plot()`, I get the following error: **RuntimeError: Failed to process string with TeX because dvipng could not be found**. Since I don't have administrator rights, I can't install dvipng via `sudo yum install dvipng`. Is there any other way to solve this problem?

**Comment by ACCarnall** [comment]
Hi, this is related to your matplotlib configuration options, you can read more here: https://matplotlib.org/stable/users/explain/text/usetex.html

You can also take a look at #14 for discussion of this, bagpipes doesn't interact as well as it could with the matplotlib config options. The guaranteed solution is to set tex_on=False on line 18 of bagpipes/plotting/general.py

**Comment by dongj17** [comment]
Hi, After I set `tex_on=False`, error disappeared. Thank you very much!
