### ISSUE TITLE
How to set this parameter "f_burst“？

### ISSUE THREAD

**Issue by dongj17** [ACCarnall/bagpipes#89]
Hi, Adam!
     I am currently performing photometric fitting on a lensed post-starburst galaxy. In the paper titled " The star formation histories of z ~1 post-starburst galaxies" (doi: 10.1093/mnras/staa674), there is a parameter "f_burst" in the equation (2). However, I couldn't find this parameter in the Bagpipes documentation. Could you please let me how to set this parameter?

**Comment by ACCarnall** [comment]
Hi Jiang,

This is a parameter of the "psb_wild2020" star-formation history model. You can see how this model works at the link below, as far as I know it's exactly as described in the paper.

https://github.com/ACCarnall/bagpipes/blob/e8fc99d39ee27e0f9e5b292fd5fb216af305a5cb/bagpipes/models/star_formation_history.py#L291

Cheers,
Adam

**Comment by lagopede** [comment]
Hi Jiang, 
An example fit_instructions for this SFH would look like this: 

    psb = {}                              # PSB model of Wild + 2020
    psb["age"] = (4, 14.)                 # Vary age between 4 and 14 Gyr. In practice 
                                          # the code automatically limits this to the age of
                                          # the Universe at the observed redshift.
    psb["tau"] = (0.3, 10.)               # Vary tau between 300 Myr and 10 Gyr
    psb["massformed"] = (6, 13)           # vary log_10(M*/M_solar) between 6 and 13
    psb["burstage"] = (0,4)               # age of burst from 0 to 4Gyr
    psb["alpha"] = (0.01,1000)               # decline of burst
    psb["alpha_prior"] = "log_10"
    psb["beta"] = 250.                    # rise of burst: fixed
    psb["fburst"] = (0,1)
    psb["metallicity"] = (0.01, 2.5)           # vary Z between 0.01 and 2.5 Z_solar
    fit_instructions["psb_wild2020"] = psb

Then the output fitted parameters for this SFH are stored in fit.posterior.samples:
'psb_wild2020:age', 'psb_wild2020:alpha', 'psb_wild2020:burstage', 'psb_wild2020:fburst', 'psb_wild2020:massformed', 'psb_wild2020:metallicity', 'psb_wild2020:tau'

Contact me by email if that isn't enough information.
