### ISSUE TITLE
Using other stellar population models instead of BC03

### ISSUE THREAD

**Issue by wzf0312** [ACCarnall/bagpipes#92]
Hello Adam, 

I am wondering if Bagpipes supports some other stellar population synthesis models like M11, or it is not available now. 

Cheers, 
WZF

**Comment by ACCarnall** [comment]
You can find a link to alternative model grid files using the BPASS library in #49. Grid files for other stellar population models don't currently exist, but users are welcome to implement other models themselves, you should be able to do this by altering the variables in the bagpipes config.py file.
