### ISSUE TITLE
How to extract the stellar_mass from a constructed SED model

### ISSUE THREAD

**Issue by May8178** [ACCarnall/bagpipes#94]
Hi,

I want to extract the value of "stellar_mass" from a SED I constructed myself, but I don't know the code to retrieve it.
I know samples from the posterior distribution for the fitted parameters are saved into the fit.posterior.samples dictionary.
However, where is 'stellar_mass from a constructed SED model' stored?

Thank you,

**Comment by ACCarnall** [comment]
Hi, I believe this should be available in model.sfh.stellar_mass.

**Comment by May8178** [comment]
Thank you for your reply.

I could extract in 
```
model = pipes.model_galaxy(model_components, filt_list=s_filt_list)
print(model.sfh.stellar_mass)

```
